---
name: Checkov
on: 
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: acitions/download-artifact@v2
        with:
          name: my-artifact
          path: ./code
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: docker
          framework: dockerfile
