---
name: Checkov
on: 
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  check:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: docker
          framework: dockerfile
