name: ci

on:
  workflow_call:
  workflow_dispatch:

jobs:
  docker:
    environment: dep
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.PWD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.USER }}/busybox:latest
          cache-from: type=registry,ref=${{ secrets.USER }}/busybox:latest
          cache-to: type=inline
