name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.deploy.DOCKERHUB_USERNAME }}
          password: ${{ secrets.deploy.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: /docker/
          push: true
          tags: rwiggs/busybox:latest
          cache-from: type=registry,ref=rwiggs/busybox:latest
          cache-to: type=inline
