name: workermagic

on:
  push:
    paths:
      - '**'

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: docker
          framework: dockerfile

  build:
    needs: check
    name: Get D
    uses: ./.github/workflows/ci.yml
