on:
  push:
    branches: [ main ]


  workflow_dispatch:


jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: checkov
        uses: ./.github/workflows/checkov.yml
