on:
  push:
    branches: [ main ]


  workflow_dispatch:


jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: upload code
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ./docker/Dockerfile
      - name: checkov
        uses: ./.github/workflows/checkov.yml
