on:
  push:
    branches: [ main ]

  workflow_dispatch:


jobs:
  
  get:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: docker
          framework: dockerfile

     
