name: workermagic
on:
  push:
    paths:
      - 'docker/*'

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: docker
          framework: dockerfile

  build:
    runs-on: ubuntu-latest

    needs: check
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          docker build ./docker/ -t busybox 
           
